### Obter tasks

GET http://localhost:3000/api/tasks

### Obter tasks finalizadas

GET http://localhost:3000/api/tasks/finished

### Criar task

POST http://localhost:3000/api/tasks
Content-Type: application/json

//status:  "pendente", "em_andamento", "finalizada"

{
    "name": "Task 1",
    "description": "Description of task 1",
    "status": "finalizada" 
}
